# Generated by Django 3.1 on 2020-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('modelopt', models.CharField(max_length=200)),
                ('plan302', models.IntegerField()),
                ('plan278', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
