# Generated by Django 3.1 on 2020-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.CharField(max_length=200, null=True)),
                ('kod', models.CharField(max_length=200, null=True)),
                ('kodd', models.IntegerField(null=True)),
                ('aa', models.IntegerField(null=True)),
                ('bb', models.IntegerField(null=True)),
                ('cc', models.IntegerField(null=True)),
                ('kodp', models.IntegerField(null=True)),
                ('dd', models.IntegerField(null=True)),
                ('ee', models.IntegerField(null=True)),
                ('proff', models.CharField(max_length=200, null=True)),
                ('smena', models.CharField(max_length=200, null=True)),
                ('kofl', models.CharField(max_length=200, null=True)),
                ('bp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fact', models.IntegerField(null=True)),
                ('facte', models.IntegerField(null=True)),
                ('factlf', models.IntegerField(null=True)),
                ('factb', models.IntegerField(null=True)),
                ('vak', models.IntegerField(null=True)),
                ('vake', models.IntegerField(null=True)),
                ('lpen', models.IntegerField(null=True)),
                ('planch', models.IntegerField(null=True)),
                ('kor', models.IntegerField(null=True)),
                ('kore', models.IntegerField(null=True)),
                ('korlf', models.IntegerField(null=True)),
                ('plane', models.IntegerField(null=True)),
                ('plaf', models.IntegerField(null=True)),
                ('planl4', models.IntegerField(null=True)),
                ('plan3', models.IntegerField(null=True)),
                ('vik', models.IntegerField(null=True)),
                ('svsh', models.IntegerField(null=True)),
                ('svbp', models.IntegerField(null=True)),
                ('diap', models.CharField(max_length=200, null=True)),
                ('kat', models.CharField(max_length=200, null=True)),
                ('katr', models.IntegerField(null=True)),
                ('katt', models.IntegerField(null=True)),
                ('katd', models.IntegerField(null=True)),
                ('ist', models.CharField(max_length=200, null=True)),
                ('tabel', models.CharField(max_length=200, null=True)),
                ('perev', models.CharField(max_length=200, null=True)),
                ('ppn', models.IntegerField(null=True)),
                ('fio', models.CharField(max_length=200, null=True)),
                ('prikas', models.CharField(max_length=200, null=True)),
                ('prik', models.CharField(max_length=200, null=True)),
                ('staj', models.IntegerField(null=True)),
                ('datap', models.IntegerField(null=True)),
                ('godr', models.IntegerField(null=True)),
                ('oklad', models.IntegerField(null=True)),
                ('kodh', models.CharField(max_length=200, null=True)),
                ('kodph', models.IntegerField(null=True)),
            ],
        ),
    ]
