# Generated by Django 3.1 on 2020-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200927_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genral',
            options={'ordering': ['url']},
        ),
        migrations.AlterField(
            model_name='genral',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genral',
            name='url',
            field=models.IntegerField(blank=True),
        ),
    ]
