# Generated by Django 3.1 on 2020-09-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200927_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uprav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.genral')),
            ],
        ),
    ]
