# Generated by Django 3.1 on 2020-09-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_uprav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uprav',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uprav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.uprav')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
